### ISSUE TITLE
Do you take donations?

### ISSUE THREAD

**Issue by TiZmSpectrum** [JHRobotics/softgpu#3]
Hi, I cannot seem to find a link towards donating to you.
My reason is since I no longer need so many 9x capable machines now I would like to give you part of my profit from selling them.
If you choose to decline allowing donations, is there any charitable event you would like people like myself to donate to?

**Comment by JHRobotics** [comment]
Hello @TiZmSpectrum,

I didn't add the sponsorship button because I didn't expect that anyone would want to contribute financially to the development of this project :-)

I added the button (direct link [ko-fi.com/jhrobotics](https://ko-fi.com/jhrobotics)), if you would like to donate, I will of course be very happy and more motivated to next development. If you don’t want to donation directly to me, please donate [Archive.org](https://archive.org/donate), they are doing great job with archiving webpage and software, and we can all benefit from their databases.

**Comment by TiZmSpectrum** [comment]
Awesome, expect a niceish size payment in the next two weeks :)

**Comment by michaeljhkim** [comment]
I highly recommend you to post a more prominent donate link because I would like to support you when I can, and I believe many others would do the same in a heartbeat. When old hardware dies out, this project will be the best solution. PC emulators, although good, are highly inefficient for the foreseeable future due to their commitment to accuracy.  
When I get the opportunity, I will be talking about this project from the highest mountain tops and promoting it to all of the people who care about this kind of thing.
